### PR TITLE
Make the clipboard commands work with multiple files/paths

### PR DESCRIPTION
**Pull request by mandx**
A new mixin is introduced to help with tasks common to a list of files.

### CODE REVIEW

**Comment by braver** [comment]
Awesome, thanks! In the feedback on the statusbar, would it be doable to show (e.g.) "Copied 3 strings to clipboard"? It's pretty elegant already, so if it's a lot of effort/loc then I'll just pull it as it is.

**Comment by mandx** [comment]
What about:
```
Copied "<content of the first line here>" and N more lines to the clipboard
```
Where `N` is 1 or greater.

**Comment by braver** [comment]
Well, in many cases you probably won't know or care what the first line of the selection is. Also, lines can be pretty long. You will probably have a clearer expectation of the number of lines in your selection, and for feedback this is concise and sufficient.

**Comment by mandx** [comment]
With this last commit, it'll show the whole text if it consists of one line, otherwise, it'll show the number of lines copied. And now is generic enough so it'll work this way with any of our commands.

**Comment by braver** [comment]
Pretty sweet!

**Pull request merged**
