### PR TITLE
Update SideBar.py

### PR DESCRIPTION
**Pull request by sharkooon**
Duplicate file with full path so it is possible to duplicate to different folder.

### CODE REVIEW

**Comment by braver** [comment]
Nifty!

**Comment by braver** [comment]
What do you think, should we stick ` (Copy)` in the new file name to give you something that works right away? I.e. have both the old and the new behaviour?

**Comment by sharkooon** [comment]
I used SideBarEnhancements allot before SideBarTools, and they didn't have (Copy) in filename when duplicate it. 

If the file is duplicated without asking filename, i would add "(Copy)" to the file name automatically, but we get prompted for a file name, so if users want to add "(Copy)", they can add it by their self.

So my opinion is to remove "(Copy)" from duplicated filename.

**Comment by braver** [comment]
Yeah, I think so too. Thanks!

**Pull request merged**
