### PR TITLE
Refactor api to something much simpler

### PR DESCRIPTION
**Pull request by rwols**
I have removed a lot of old cruft after you gutted the original repo. SideBarAPI.py is now completely gone, as it isn't actually needed anywhere. The whole thing is now just about 100 lines of python code.

### CODE REVIEW

**Comment by rwols** [comment]
I seem to have missed checking the "Open With Default" command as it doesn't work right now; let me fix that

**Comment by rwols** [comment]
Actually, instead of spending time on getting this "Open With Default" thing working, why not just inform users to download [this package](https://packagecontrol.io/packages/Open%20in%20Default%20Application)?

**Comment by braver** [comment]
OK, 😳 wow... thanks!

I didn't know about that package, but it seems like the way to go. Kinda forgot about Windows compatibility there. 

I'm gonna test this and then merge asap!

**Comment by rwols** [comment]
You're welcome!

**Comment by braver** [comment]
@rwols it seems duplicating directories has been broken by this.

**Comment by braver** [comment]
Nevermind, I think I got it. Gotta use `copytree` for dirs.

**Comment by rwols** [comment]
Right... I only tested that with single files. `shutil.copytree` is a good solution 💯

**Pull request merged**
