### PR TITLE
Allow difftools with more subcommands to be used

### PR DESCRIPTION
**Pull request by kortschak**
This allows smerge mergetool to be used as a compare tool by giving the config "difftool": ["smerge", "mergetool"].

### CODE REVIEW

**Comment by braver** [comment]
Oh, nice! Can you add some info to the default setting that explains you can set either a string, or an array to pass parameters?

**Comment by kortschak** [comment]
PTAL

**Comment by kortschak** [comment]
Travis is no longer happy with this. Do you want me to change the comparison?

The flakes are in code I have not changed.

**Comment by braver** [comment]
Yes please, let's keep flake8 happy :)

**Comment by kortschak** [comment]
Done

**Comment by braver** [comment]
🎉 💯

**Pull request merged**
