### PR TITLE
Add Edit menu item

### PR DESCRIPTION
**Pull request by PetrKryslUCSD**

### CODE REVIEW

**Comment by PetrKryslUCSD** [comment]
Btw: I don't know how to hide this under a setting (to make it optional). Sorry.

**Comment by mandx** [comment]
Isn't this the same as just clicking on the sidebar item?

**Comment by PetrKryslUCSD** [comment]
It is. But that is hard to do when operating the editor with a finger
(Surface Pro, for instance).

**Comment by braver** [comment]
It's added, but disabled by default. See here for more info: https://github.com/braver/SideBarTools/commit/f083c1e5cf82f02b2889b5d134077ef47163f547

**Pull request merged**
